@startuml

title __MYTUBE's Class Diagram__\n

  namespace com.mytube {
    class com.mytube.EmailService {
        + notify()
    }
  }
  

  namespace com.mytube {
    class com.mytube.Main {
        {static} + main()
    }
  }
  

  namespace com.mytube {
    interface com.mytube.NotificationService {
        {abstract} + notify()
    }
  }
  

  namespace com.mytube {
    class com.mytube.SqlVideoDatabase {
        + store()
    }
  }
  

  namespace com.mytube {
    class com.mytube.User {
        - email : String
        + User()
        + getEmail()
        + setEmail()
    }
  }
  

  namespace com.mytube {
    class com.mytube.Video {
        - fileName : String
        - title : String
        - user : User
        + getFileName()
        + getTitle()
        + getUser()
        + setFileName()
        + setTitle()
        + setUser()
    }
  }
  

  namespace com.mytube {
    interface com.mytube.VideoDatabase {
        {abstract} + store()
    }
  }
  

  namespace com.mytube {
    interface com.mytube.VideoEncoder {
        {abstract} + encode()
    }
  }
  

  namespace com.mytube {
    class com.mytube.VideoProcessor {
        - database : VideoDatabase
        - encoder : VideoEncoder
        - notificationService : NotificationService
        + VideoProcessor()
        + process()
    }
  }
  

  namespace com.mytube {
    class com.mytube.XVideoEncoder {
        + encode()
    }
  }
  

  com.mytube.EmailService .up.|> NotificationService
  com.mytube.SqlVideoDatabase .up.|> VideoDatabase
  com.mytube.XVideoEncoder .up.|> VideoEncoder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
